### ISSUE TITLE
Crash on Node v16

### ISSUE THREAD

**Issue by mcollina** [clinicjs/node-clinic-bubbleprof#388]
Using the following script:

```js
const { fetch } = require(".");
const { isMainThread } = require('worker_threads');
const os = require('os');

const main = async () => {
    const res = await fetch("https://jsonplaceholder.typicode.com/posts/1");
    const json = await res.json();

    main();
};

main();
main();
main();
main();
main();

if (isMainThread) {
  setInterval(() => {
      console.log(os.freemem());
  }, 1000)
}
```

It crashes with:

```sh
$ clinic bubble -- node worker.js
To generate the report press: Ctrl + C
(node:64049) [DEP0111] DeprecationWarning: Access to process.binding('async_wrap') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
Warning: The code is transpiled, bubbleprof does not support source maps yet.
(node:64049) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
Error: typeName is required
    at Object.encodingLength (eval at line.toFunction (/Users/matteo/.nvm/versions/node/v16.13.0/lib/node_modules/clinic/node_modules/generate-function/index.js:172:21), <anonymous>:8:37)
    at Object.encodingLength (eval at line.toFunction (/Users/matteo/.nvm/versions/node/v16.13.0/lib/node_modules/clinic/node_modules/generate-function/index.js:172:21), <anonymous>:11:24)
    at StackTraceEncoder._transform (/Users/matteo/.nvm/versions/node/v16.13.0/lib/node_modules/clinic/node_modules/@clinic/bubbleprof/format/abstract-encoder.js:18:45)
    at StackTraceEncoder.Transform._write (node:internal/streams/transform:184:23)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at StackTraceEncoder.Writable.write (node:internal/streams/writable:334:10)
    at AsyncHook.init (/Users/matteo/.nvm/versions/node/v16.13.0/lib/node_modules/clinic/node_modules/@clinic/bubbleprof/injects/logger.js:53:13)
    at BrotliDecoder.emitInitNative (node:internal/async_hooks:205:43)
    at BrotliDecompress.Brotli (node:zlib:839:5)
```

**Comment by RafaelGSS** [comment]
@mcollina It's not because worker_threads is not supported? 

See: https://github.com/clinicjs/node-clinic/issues/213

**Comment by mcollina** [comment]
We are just calling isMainThread, we are not using threads at all. I'll try anyway.
