### ISSUE TITLE
TypeError: structuredStackTrace.map is not a function

### ISSUE THREAD

**Issue by kyoungduck** [clinicjs/node-clinic-bubbleprof#397]
I got error in this command.

```
clinic bubbleprof --on-port 'k6 run k6/search.js --vus 10 --duration 10s' -- node -r ./.pnp.cjs dist/main.js
```

Error: 
```
TypeError: structuredStackTrace.map is not a function
    at stackTrace (/Users/peter/.nvm/versions/node/v16.13.2/lib/node_modules/clinic/node_modules/@clinic/bubbleprof/collect/stack-trace.js:77:39)
    at AsyncHook.init (/Users/peter/.nvm/versions/node/v16.13.2/lib/node_modules/clinic/node_modules/@clinic/bubbleprof/injects/logger.js:56:15)
    at Zlib.emitInitNative (node:internal/async_hooks:205:43)
    at InflateRaw.Zlib (node:zlib:681:18)
    at new InflateRaw (node:zlib:775:3)
    at Object.syncBufferWrapper [as inflateRawSync] (node:zlib:791:29)
    at ZipFS.getFileSource (/Users/peter/Documents/project/daangn/realty/server/.pnp.cjs:31396:60)
    at ZipFS.readFileBuffer (/Users/peter/Documents/project/daangn/realty/server/.pnp.cjs:31716:17)
    at ZipFS.readFileSync (/Users/peter/Documents/project/daangn/realty/server/.pnp.cjs:31702:23)
    at /Users/peter/Documents/project/daangn/realty/server/.pnp.cjs:32600:20
process exited with exit code 1
Analysing data
```

node-doctor and node-flame works well, but only bubbleprof gets this error. I think there's some problem at pnp mode.

My Environment:
- os: macOS Monterey 12.1
- node: v16.13.2
- yarn: v3, pnp mode
- bubbleprof: v8.0.1
- clinic: v11.1.0

**Comment by RafaelGSS** [comment]
Are you able to send a reproductible code?
